# Generated by Django 3.1.4 on 2021-01-27 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210125_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aktivation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 16, 53, 1, 401636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
